/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eztagclient;

//import eztagserver.*;
import eztagserver.Customer;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.*;
//import eztagclient.*;

/**
 *
 * @author red
 */
public class LoginUI extends javax.swing.JFrame {
    Socket sock = null;
    //ObjectOutputStream output = null;
    //ObjectInputStream input = null;
    String msg = "Login";


    /**
     * Creates new form Login
     */
    public LoginUI() {
        try{
            Socket sock = new Socket(EZTag.SERVER, EZTag.SERVER_PORT);
            //socket = sock;
            //final ObjectOutputStream output = new ObjectOutputStream(sock.getOutputStream());
            //final ObjectInputStream input = new ObjectInputStream(sock.getInputStream());
            EZTag.output = new ObjectOutputStream(sock.getOutputStream());
            EZTag.input = new ObjectInputStream(sock.getInputStream());
            EZTag.output.writeObject(msg);
            initComponents();
            this.setLocationRelativeTo(null);
        }catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace(System.err);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diaNoAcc = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        btnCloseAcc = new javax.swing.JButton();
        diaInvalidLogin = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        btnCloseLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnGo = new javax.swing.JButton();

        diaNoAcc.setMinimumSize(new java.awt.Dimension(584, 155));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel5.setText("Invalid Account Number!");

        btnCloseAcc.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        btnCloseAcc.setText("OK");
        btnCloseAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseAccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaNoAccLayout = new javax.swing.GroupLayout(diaNoAcc.getContentPane());
        diaNoAcc.getContentPane().setLayout(diaNoAccLayout);
        diaNoAccLayout.setHorizontalGroup(
            diaNoAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaNoAccLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(diaNoAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(btnCloseAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        diaNoAccLayout.setVerticalGroup(
            diaNoAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaNoAccLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnCloseAcc)
                .addGap(26, 26, 26))
        );

        diaInvalidLogin.setMinimumSize(new java.awt.Dimension(584, 155));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel6.setText("Invalid Username or Password!");

        btnCloseLogin.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        btnCloseLogin.setText("OK");
        btnCloseLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaInvalidLoginLayout = new javax.swing.GroupLayout(diaInvalidLogin.getContentPane());
        diaInvalidLogin.getContentPane().setLayout(diaInvalidLoginLayout);
        diaInvalidLoginLayout.setHorizontalGroup(
            diaInvalidLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaInvalidLoginLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(diaInvalidLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(btnCloseLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        diaInvalidLoginLayout.setVerticalGroup(
            diaInvalidLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaInvalidLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnCloseLogin)
                .addGap(24, 24, 24))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Username:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password:");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnGo.setText("Go!");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtUsername)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtPassword, txtUsername});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGo)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, txtPassword, txtUsername});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new EZTag().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
        /*if(Customer.verify(Integer.parseInt(txtAccountNumber.getText()), txtUsername.getText(), txtPassword.getText())){
            new AccountUI(Integer.parseInt(txtAccountNumber.getText())).setVisible(true);
        }*/
        try{
            //final ObjectOutputStream output = new ObjectOutputStream(sock.getOutputStream());
            //final ObjectInputStream input = new ObjectInputStream(sock.getInputStream());
            msg = txtUsername.getText();
            EZTag.output.writeObject(msg);
            msg = txtPassword.getText();
            EZTag.output.writeObject(msg);
            msg = (String)EZTag.input.readObject();
            if(msg.equals("Customer")){
                new AccountUI((Customer)EZTag.input.readObject(), sock, false).setVisible(true);
                dispose();
            }
            if(msg.equals("Employee")){
                new EmployeeUI().setVisible(true);
                dispose();
            }
            if(msg.equals("Invalid")){
                diaInvalidLogin.setVisible(true);
                diaInvalidLogin.setLocationRelativeTo(null);
            }
        }catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace(System.err);
        }
    }//GEN-LAST:event_btnGoActionPerformed

    private void btnCloseAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseAccActionPerformed
        // TODO add your handling code here:
        diaNoAcc.dispose();
    }//GEN-LAST:event_btnCloseAccActionPerformed

    private void btnCloseLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseLoginActionPerformed
        // TODO add your handling code here:
        diaInvalidLogin.dispose();
    }//GEN-LAST:event_btnCloseLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseAcc;
    private javax.swing.JButton btnCloseLogin;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGo;
    private javax.swing.JDialog diaInvalidLogin;
    private javax.swing.JDialog diaNoAcc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
